### ISSUE TITLE
Big package

### ISSUE THREAD

**Issue by danielgomezrico** [michelelacorte/ElasticProgressBar#1]
I know that it sounds not important but 

`compile 'com.example.michele.michelelacorteelasticprogressbar:michelelacorteelasticprogressbar:1.0.2@aar'`

it is not so big?

**Comment by michelelacorte** [comment]
Of course , thanks to the alert , I had some problems compiling the library that's why all that name , I'll try to solve in the next versions! Thanks.

**Comment by danielgomezrico** [comment]
:+1:
