### ISSUE TITLE
VectorDrawable: parser error

### ISSUE THREAD

**Issue by Celggar** [michelelacorte/ElasticProgressBar#2]
When I use a pre-lollipop device application displays the following exception:

VectorDrawable: parser error
org.xmlpull.v1.XmlPullParserException: Binary XML file line #2<menu_vector> tag requires viewportWidth > 0
at it.michelelacorte.elasticprogressbar.VectorCompat.VectorDrawable.updateStateFromTypedArray(VectorDrawable.java:355)
...
Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class it.michelelacorte.elasticprogressbar.ElasticDownloadView

This does not happen when I use the library Guégan Thibault (Tibolte) with exactly the same scenario, however the level of customization that has added you, I think is excellent and really want to use this library in the project I'm currently developing.

Sorry for my English and thank you very much for your great work.

**Comment by michelelacorte** [comment]
First of all thanks for the tip @Ceaggar , now you would say that API uses? 
However I will try to solve it as soon as possible, I'm glad you like it!!!

**Comment by Celggar** [comment]
I am using 'it.michelelacorte.elasticprogressbar:library:1.0.4'
In the following devices:
- LG-E450g with android 4.1.2 (error)
- LG-D855 device with android 4.4.2 (error)
- Samsung GT-I9190 with android 5.1.1 (extremely well)
- LG Nexus 5 with android 6.0 (extremely well, too).

thanks for the speed of your response.

**Comment by michelelacorte** [comment]
@Ceaggar  Thanks to you, I'll try to solve as soon as possible!

**Comment by michelelacorte** [comment]
@Ceaggar I found a solution, I missed a simple configuration in xml file, tomorrow I think I put a minor update for you :D

**Comment by Celggar** [comment]
Thank you very much!

**Comment by michelelacorte** [comment]
I've updated the library , thanks again , and if you have any other problem do not hesitate to report it!
