### ISSUE TITLE
Hi mate! Error in parsing "g/"

### ISSUE THREAD

**Issue by iRYO400** [michelelacorte/ElasticProgressBar#3]
After syncing gradle, I get this error:
Error:Execution failed for task ':app:mergeDebugResources'.

> J:\Workspace_V3\FlashFire\app\build\intermediates\exploded-aar\it.michelelacorte.elasticprogressbar\library\1.0.5\res\drawable\vd_start.xml: Error: error in parsing "g/"

I dunno what is it

**Comment by iRYO400** [comment]
Help!

**Comment by michelelacorte** [comment]
Please tell me that API uses and how are you using the library

**Comment by iRYO400** [comment]
I use Android Studio 1.5.3
Library connected via both ways:
1) `compile  'it.michelelacorte.elasticprogressbar:library:1.0.5'`
2) 

```
allprojects {
    repositories {
        maven { url "https://dl.bintray.com/michelelacorte/maven/" }
        jcenter()
        mavenCentral()

    }
}
compile  'it.michelelacorte.elasticprogressbar:library:1.0.5@aar'
```

I tested it in a new Blank and in my Main projects. And get the same error

**Comment by michelelacorte** [comment]
replace your build.gradle (app) with:

```
apply plugin: 'com.android.application'

allprojects {
    repositories {
        maven { url "https://dl.bintray.com/michelelacorte/maven/" }
        jcenter()
        mavenCentral()

    }
}
android {
    compileSdkVersion 23
    buildToolsVersion '23.0.2'
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
   //other dependencies
    compile  'it.michelelacorte.elasticprogressbar:library:1.0.5@aar'
}

```

Or just add in dependencies:

`compile  'it.michelelacorte.elasticprogressbar:library:1.0.5'`

**Comment by iRYO400** [comment]
It still get error

```
Error:Error: error in parsing "g/"
:app:mergeDebugResources FAILED
Error:Execution failed for task ':app:mergeDebugResources'.
> J:\Workspace_V3\ElasticTest\app\build\intermediates\exploded-aar\it.michelelacorte.elasticprogressbar\library\1.0.5\res\drawable\vd_start.xml: Error: error in parsing "g/"
```

**Comment by michelelacorte** [comment]
It's look strange...Please contact me by e-mail: micky1995g@gmail.com

**Comment by michelelacorte** [comment]
You have to add on  `defaultConfig` tag in your `build.gradle` this line:

   `generatedDensities = []`

**Comment by iRYO400** [comment]
Solved! Thanks again!

**Comment by michelelacorte** [comment]
Close and add in README file! Thanks for reporting

**Comment by AshishPsaini** [comment]
vectorDrawables.useSupportLibrary = true is missing in defaultConfig { } . 
Please add below lines in build.gradle in defualt config .

defaultConfig {
        minSdkVersion 14
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true

```
}
```

or 

 vectorDrawables.useSupportLibrary = true  in defaultConfig { } block in build.gradle
