### ISSUE TITLE
At first start "noBackground" doesn't work

### ISSUE THREAD

**Issue by iRYO400** [michelelacorte/ElasticProgressBar#4]
At first start "noBackground" doesn't work and uses default colors.(( 
How I implemented it in onCreate()

```
setContentView(R.layout.activity_launcher);
OptionView.noBackground = true;
```

thx

**Comment by michelelacorte** [comment]
You have to set option with `OptionView` class before `setContentView(..)`

**Comment by iRYO400** [comment]
eazy breezy...
thx
